name: abfe
channels:
  - bioconda
  - michellab/label/dev
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - conda-build
  
  - snakemake=7.8.5
  - tabulate=0.8.10
  
  #- cuda-toolkit=11.4.2
  - gromacs=2022.2

  - matplotlib
  - numpy
  - scipy
  - pandas
  
  - mdanalysis
  - parmed
  - pdbfixer
  - biosimspace
  - sire=2023.0.2
  - openff-toolkit
  - openff-interchange

  - pip:
    - alchemlyb==2.0.0
    - pymbar==4.0.1
    - MDRestraintsGenerator

