name: abfe
channels:
  - bioconda
  - michellab/label/dev
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.8.4=py39h72bdee0_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - ambertools=22.0=py39h464e725_3
  - amply=0.1.5=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arpack=3.7.0=hdefa2d7_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attmap=0.13.2=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py39hb9d737c_1
  - beautifulsoup4=4.12.0=pyha770c72_0
  - biopython=1.81=py39h72bdee0_0
  - biosimspace=2023.1.1=py39_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - boto3=1.26.101=pyhd8ed1ab_0
  - botocore=1.29.101=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - cftime=1.6.2=py39h2ae25f5_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=h6f57e76_2
  - coin-or-clp=1.17.7=hc56784d_2
  - coin-or-osi=0.108.7=h2720bb7_2
  - coin-or-utils=2.11.6=h202d8b1_2
  - coincbc=2.10.8=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - cryptography=40.0.1=py39h079d5ae_0
  - cudatoolkit=11.8.0=h37601d7_11
  - curl=7.88.1=hdc1c0ab_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.33=py39h227be39_0
  - datrie=0.8.2=py39hb9d737c_6
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.6=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.17.1=py39hf3d152e_3
  - dpath=2.1.5=py39hf3d152e_0
  - dropbox=11.36.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filechunkio=1.8=py_2
  - filelock=3.10.7=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3=py39h72bdee0_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.3=py39hb9d737c_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - google-api-core=2.11.0=pyhd8ed1ab_0
  - google-api-python-client=2.83.0=pyhd8ed1ab_0
  - google-auth=2.17.0=pyh1a96a4e_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.7.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py39h8db88ab_4
  - google-resumable-media=2.4.1=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=7.1.0=h2e5815a_0
  - greenlet=2.0.2=py39h227be39_0
  - griddataformats=1.0.1=pyhd8ed1ab_0
  - gromacs=2022.2=nompi_hca75aac_100
  - grpcio=1.52.1=py39h227be39_1
  - gsd=2.8.0=py39h389d5f1_0
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.33=h166bdaf_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py39hf3d152e_4
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.14.0=py39hef51801_0
  - ipython=8.4.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.5=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hf3d152e_8
  - jupyter_client=8.1.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hf3d152e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.4=pyhd8ed1ab_0
  - kcombu_bss=2022.06.10=h9bf148f_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lazy_import=0.2.2=pyhd8ed1ab_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.0=cxx17_hcb278e6_1
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.88.1=hdc1c0ab_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h5aea950_4
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.46=h620e276_0
  - libgrpc=1.52.1=hcf146ea_1
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.2=hb675445_0
  - libprotobuf=3.21.12=h3eb15da_0
  - librsvg=2.54.4=h7abd40a_0
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - logmuse=0.2.6=pyh8c360ce_0
  - lomap2=2.1.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib-base=3.7.1=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdanalysis=2.4.2=py39h5ea5205_0
  - mdtraj=1.9.7=py39h62423bb_4
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpg123=1.31.3=hcb278e6_0
  - mrcfile=1.4.3=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - multidict=6.0.4=py39h72bdee0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=ha901b37_1
  - mysql-libs=8.0.32=hd7da12d_1
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.10=pyhd8ed1ab_1
  - nbconvert-core=7.2.10=pyhd8ed1ab_1
  - nbconvert-pandoc=7.2.10=pyhd8ed1ab_1
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nbsphinx=0.8.7=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf-fortran=4.6.0=nompi_he1eeb6f_102
  - netcdf4=1.6.2=nompi_py39hfaa66c4_100
  - networkx=3.0=pyhd8ed1ab_0
  - nglview=3.0.3=pyh8a188c0_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - oauth2client=4.1.3=py_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openff-amber-ff-ports=0.0.3=pyh6c4a22f_0
  - openff-forcefields=2023.02.1=pyh1a96a4e_0
  - openff-interchange=0.2.3=pyhd8ed1ab_1
  - openff-interchange-base=0.2.3=pyhd8ed1ab_1
  - openff-toolkit=0.12.1=pyhd8ed1ab_1
  - openff-toolkit-base=0.12.1=pyhd8ed1ab_1
  - openff-units=0.2.0=pyh1a96a4e_0
  - openff-utilities=0.1.8=pyh1a96a4e_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openmm=8.0.0=py39hc5dd2c2_0
  - openssl=3.1.0=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - packmol=20.010=h86c2bf4_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panedr=0.7.1=pyhd8ed1ab_0
  - pango=1.50.14=hd33c08f_0
  - paramiko=3.1.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pbr=5.11.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pdbfixer=1.8.1=pyh6c4a22f_0
  - peppy=0.35.5=pyhd8ed1ab_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py39hde42818_1002
  - pillow=9.4.0=py39h2320bf1_1
  - pint=0.20.1=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py39hf3d152e_4
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - prettytable=3.6.0=pyhd8ed1ab_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py39hf3d152e_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py3dmol=2.0.1.post1=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycairo=1.23.0=py39h23c5bb2_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.7=py39h72bdee0_0
  - pydot=1.4.2=py39hf3d152e_3
  - pyedr=0.7.1=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pygtail=0.14.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py39hb9d737c_2
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pypdb=2.2=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py39hf3d152e_5
  - pytables=3.7.0=py39h6a7961f_3
  - pytest=7.2.2=pyhd8ed1ab_0
  - python=3.9.16=h2782a2a_0_cpython
  - python-constraint=1.4.0=py_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-irodsclient=1.1.6=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytng=0.3.0=py39h0050040_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.2=py39h0be026e_0
  - qt=5.15.8=hf11cfaa_0
  - qt-main=5.15.8=h5d23da1_6
  - qt-webengine=5.15.8=h77d6d84_0
  - qtconsole=5.4.1=pyhd8ed1ab_0
  - qtconsole-base=5.4.1=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - rdkit=2022.09.1=py39h79face8_0
  - re2=2023.02.02=hcb278e6_0
  - readline=8.2=h8228510_1
  - reportlab=3.6.12=py39h8bbe095_2
  - requests=2.28.2=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.3.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py39hd189fd4_1
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - sip=6.7.7=py39h227be39_0
  - sire=2023.1.2=py39h3fd9d12_1
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - smirnoff99frosst=1.1.0=pyh44b312d_0
  - smmap=3.0.5=pyh44b312d_0
  # Removed pin
  - snakemake
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=4.1.2=pyh6c4a22f_1
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlalchemy=2.0.7=py39h72bdee0_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h2ae25f5_2
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tbb=2021.7.0=h924138e_1
  - tbb-devel=2021.7.0=h924138e_1
  - terminado=0.15.0=py39hf3d152e_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - throttler=1.2.1=pyhd8ed1ab_0
  - tidynamics=1.0.0=py_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - watchdog=3.0.0=py39hf3d152e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=3.6.4=pyhd8ed1ab_0
  - wrapt=1.15.0=py39h72bdee0_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.2=py39hb9d737c_0
  - yte=1.5.1=py39hf3d152e_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - alchemlyb==2.0.0
    - amberlite==22.0
    - amberutils==21.0
    - commonmark==0.9.1
    - fasteners==0.18
    - jax==0.4.7
    - jaxlib==0.4.7
    - mdrestraintsgenerator==0.2.1
    - ml-dtypes==0.0.4
    - mmpbsa-py==16.0
    - numexpr==2.8.4
    - numpy==1.22.4
    - opt-einsum==3.3.0
    - packmol-memgen==1.2.3rc0
    - pandas==1.5.3
    - parmed==4.0.0
    - pdb4amber==22.0
    - pymbar==4.0.1
    - pytraj==2.0.6
    - pytz==2023.3
    - recommonmark==0.7.1
    - sander==22.0
    - scipy==1.7.3
    - sphinx-rtd-theme==1.2.0
    - sphinxcontrib-jquery==4.1
    - tabulate==0.8.10
    - toff==0.0.2
    # The workflow from the repo
    - git+https://github.com/ale94mleon/ABFE_workflow.git@dev
