name: abfe
channels:
  - conda-forge
dependencies:
  - python >=3.8, <3.10 # biosimspace use this python definition
  - pip
  - gromacs=2022.2
  - parmed
  - pdbfixer
  - openmm
  - openff-toolkit
  - michellab/label/dev::biosimspace
  - bioconda::snakemake
  # - nvidia::cuda-toolkit=11.4.2
  - pip:
    - git+https://github.com/ale94mleon/ABFE_workflow.git@dev
